export const INGREDIENTS_REQUEST:
    'INGREDIENTS_REQUEST' = 'INGREDIENTS_REQUEST' as const;

export const INGREDIENTS_REQUEST_SUCCESS:
    'INGREDIENTS_REQUEST_SUCCESS' = 'INGREDIENTS_REQUEST_SUCCESS' as const;

export const INGREDIENTS_REQUSET_FAILED:
    'INGREDIENTS_REQUSET_FAILED' = 'INGREDIENTS_REQUSET_FAILED' as const;

export const SHOW_INGREDIENT_INFO:
    'SHOW_INGREDIENT_INFO' = 'SHOW_INGREDIENT_INFO' as const;

export const CLEAR_INGREDIENT_INFO:
    'CLEAR_INGREDIENT_INFO' = 'CLEAR_INGREDIENT_INFO' as const;
