export const OPEN_INGREDIENT_MODAL:
    'OPEN_INGREDIENT_MODAL' = 'OPEN_INGREDIENT_MODAL' as const;

export const OPEN_ORDER_RESULT_MODAL:
    'OPEN_ORDER_RESULT_MODAL' = 'OPEN_ORDER_RESULT_MODAL' as const;

export const OPEN_ORDER_DETAILS_MODAL:
    'OPEN_ORDER_DETAILS_MODAL' = 'OPEN_ORDER_DETAILS_MODAL' as const;

export const OPEN_USER_REGISTER_MODAL:
    'OPEN_USER_REGISTER_MODAL' = 'OPEN_USER_REGISTER_MODAL' as const;

export const OPEN_USER_LOGIN_MODAL:
    'OPEN_USER_LOGIN_MODAL' = 'OPEN_USER_LOGIN_MODAL' as const;

export const OPEN_USER_LOGOUT_MODAL:
    'OPEN_USER_LOGOUT_MODAL' = 'OPEN_USER_LOGOUT_MODAL' as const;

export const OPEN_USER_FORGOT_PASSWORD_MODAL:
    'OPEN_USER_FORGOT_PASSWORD_MODAL' = 'OPEN_USER_FORGOT_PASSWORD_MODAL' as const;

export const OPEN_USER_RESET_PASSWORD_MODAL:
    'OPEN_USER_RESET_PASSWORD_MODAL' = 'OPEN_USER_RESET_PASSWORD_MODAL' as const;

export const OPEN_USER_LOAD_MODAL:
    'OPEN_USER_LOAD_MODAL' = 'OPEN_USER_LOAD_MODAL' as const;

export const OPEN_USER_SAVE_MODAL:
    'OPEN_USER_SAVE_MODAL' = 'OPEN_USER_SAVE_MODAL' as const;

export const CLOSE_MODAL:
    'CLOSE_MODAL' = 'CLOSE_MODAL' as const;
