export const MAKE_ORDER_REQUEST:
    'MAKE_ORDER_REQUEST' = 'MAKE_ORDER_REQUEST' as const;

export const MAKE_ORDER_REQUEST_SUCCESS:
    'MAKE_ORDER_REQUEST_SUCCESS' = 'MAKE_ORDER_REQUEST_SUCCESS' as const;

export const MAKE_ORDER_REQUEST_FAILED:
    'MAKE_ORDER_REQUEST_FAILED' = 'MAKE_ORDER_REQUEST_FAILED' as const;

export const CLEAR_ORDER_RESULT:
    'CLEAR_ORDER_RESULT' = 'CLEAR_ORDER_RESULT' as const;

export const CLEAR_ORDER_ERROR:
    'CLEAR_ORDER_ERROR' = 'CLEAR_ORDER_ERROR' as const;
