export const USER_REGISTER_REQUEST:
    'USER_REGISTER_REQUEST' = 'USER_REGISTER_REQUEST' as const;

export const USER_REGISTER_REQUEST_SUCCESS:
    'USER_REGISTER_REQUEST_SUCCESS' = 'USER_REGISTER_REQUEST_SUCCESS' as const;

export const USER_REGISTER_REQUEST_FAILED:
    'USER_REGISTER_REQUEST_FAILED' = 'USER_REGISTER_REQUEST_FAILED' as const;

export const CLEAR_USER_REGISTER_REQUEST_FAILED:
    'CLEAR_USER_REGISTER_REQUEST_FAILED' = 'CLEAR_USER_REGISTER_REQUEST_FAILED' as const;


export const USER_LOGIN_REQUEST:
    'USER_LOGIN_REQUEST' = 'USER_LOGIN_REQUEST' as const;

export const USER_LOGIN_REQUEST_SUCCESS:
    'USER_LOGIN_REQUEST_SUCCESS' = 'USER_LOGIN_REQUEST_SUCCESS' as const;

export const USER_LOGIN_REQUEST_FAILED:
    'USER_LOGIN_REQUEST_FAILED' = 'USER_LOGIN_REQUEST_FAILED' as const;

export const CLEAR_USER_LOGIN_REQUEST_FAILED:
    'CLEAR_USER_LOGIN_REQUEST_FAILED' = 'CLEAR_USER_LOGIN_REQUEST_FAILED' as const;


export const USER_LOGOUT_REQUEST:
    'USER_LOGOUT_REQUEST' = 'USER_LOGOUT_REQUEST' as const;

export const USER_LOGOUT_REQUEST_SUCCESS:
    'USER_LOGOUT_REQUEST_SUCCESS' = 'USER_LOGOUT_REQUEST_SUCCESS' as const;

export const USER_LOGOUT_REQUEST_FAILED:
    'USER_LOGOUT_REQUEST_FAILED' = 'USER_LOGOUT_REQUEST_FAILED' as const;

export const CLEAR_USER_LOGOUT_REQUEST_FAILED:
    'CLEAR_USER_LOGOUT_REQUEST_FAILED' = 'CLEAR_USER_LOGOUT_REQUEST_FAILED' as const;


export const USER_FORGOT_PASSWORD_REQUEST:
    'USER_FORGOT_PASSWORD_REQUEST' = 'USER_FORGOT_PASSWORD_REQUEST' as const;

export const USER_FORGOT_PASSWORD_REQUEST_SUCCESS:
    'USER_FORGOT_PASSWORD_REQUEST_SUCCESS' = 'USER_FORGOT_PASSWORD_REQUEST_SUCCESS' as const;

export const USER_FORGOT_PASSWORD_REQUEST_FAILED:
    'USER_FORGOT_PASSWORD_REQUEST_FAILED' = 'USER_FORGOT_PASSWORD_REQUEST_FAILED' as const;

export const CLEAR_USER_FORGOT_PASSWORD_REQUEST_FAILED:
    'CLEAR_USER_FORGOT_PASSWORD_REQUEST_FAILED' =
    'CLEAR_USER_FORGOT_PASSWORD_REQUEST_FAILED' as const;

export const CLEAR_USER_FORGOT_PASSWORD_RESULT:
    'CLEAR_USER_FORGOT_PASSWORD_RESULT' = 'CLEAR_USER_FORGOT_PASSWORD_RESULT' as const;


export const USER_RESET_PASSWORD_REQUEST:
    'USER_RESET_PASSWORD_REQUEST' = 'USER_RESET_PASSWORD_REQUEST' as const;
export const USER_RESET_PASSWORD_REQUEST_SUCCESS:
    'USER_RESET_PASSWORD_REQUEST_SUCCESS' = 'USER_RESET_PASSWORD_REQUEST_SUCCESS' as const;

export const USER_RESET_PASSWORD_REQUEST_FAILED:
    'USER_RESET_PASSWORD_REQUEST_FAILED' = 'USER_RESET_PASSWORD_REQUEST_FAILED' as const;

export const CLEAR_USER_RESET_PASSWORD_REQUEST_FAILED:
    'CLEAR_USER_RESET_PASSWORD_REQUEST_FAILED' =
    'CLEAR_USER_RESET_PASSWORD_REQUEST_FAILED' as const;


export const USER_LOAD_DATA_REQUEST:
    'USER_LOAD_DATA_REQUEST' = 'USER_LOAD_DATA_REQUEST' as const;

export const USER_LOAD_DATA_REQUEST_SUCCESS:
    'USER_LOAD_DATA_REQUEST_SUCCESS' = 'USER_LOAD_DATA_REQUEST_SUCCESS' as const;

export const USER_LOAD_DATA_REQUEST_FAILED:
    'USER_LOAD_DATA_REQUEST_FAILED' = 'USER_LOAD_DATA_REQUEST_FAILED' as const;

export const CLEAR_USER_LOAD_DATA_REQUEST_FAILED:
    'CLEAR_USER_LOAD_DATA_REQUEST_FAILED' = 'CLEAR_USER_LOAD_DATA_REQUEST_FAILED' as const;


export const USER_SAVE_DATA_REQUEST:
    'USER_SAVE_DATA_REQUEST' = 'USER_SAVE_DATA_REQUEST' as const;

export const USER_SAVE_DATA_REQUEST_SUCCESS:
    'USER_SAVE_DATA_REQUEST_SUCCESS' = 'USER_SAVE_DATA_REQUEST_SUCCESS' as const;

export const USER_SAVE_DATA_REQUEST_FAILED:
    'USER_SAVE_DATA_REQUEST_FAILED' = 'USER_SAVE_DATA_REQUEST_FAILED' as const;

export const CLEAR_USER_SAVE_DATA_REQUEST_FAILED:
    'CLEAR_USER_SAVE_DATA_REQUEST_FAILED' = 'CLEAR_USER_SAVE_DATA_REQUEST_FAILED' as const;
