export const WS_ALL_ORDERS_CONNECTION_START:
    'WS_ALL_ORDERS_CONNECTION_START' = 'WS_ALL_ORDERS_CONNECTION_START' as const;

export const WS_ALL_ORDERS_CONNECTION_SUCCESS:
    'WS_ALL_ORDERS_CONNECTION_SUCCESS' = 'WS_ALL_ORDERS_CONNECTION_SUCCESS' as const;

export const WS_ALL_ORDERS_CONNECTION_ERROR:
    'WS_ALL_ORDERS_CONNECTION_ERROR' = 'WS_ALL_ORDERS_CONNECTION_ERROR' as const;

export const WS_ALL_ORDERS_CONNECTION_CLOSED:
    'WS_ALL_ORDERS_CONNECTION_CLOSED' = 'WS_ALL_ORDERS_CONNECTION_CLOSED' as const;

export const WS_GET_ALL_ORDERS:
    'WS_GET_ALL_ORDERS' = 'WS_GET_ALL_ORDERS' as const;

export const WS_SHOW_ORDERS_DETAILS:
    'WS_SHOW_ORDERS_DETAILS' = 'WS_SHOW_ORDERS_DETAILS' as const;

export const WS_CLEAR_ORDERS_DETAILS:
    'WS_CLEAR_ORDERS_DETAILS' = 'WS_CLEAR_ORDERS_DETAILS' as const;
